### ISSUE TITLE
[a11y] Contrast - Courses

### ISSUE THREAD

**Issue by tdy** [cs-education/classTranscribe#63]
Courses URL: https://classtranscribe.ncsa.illinois.edu/courses

Color contrast ratio (CCR) needs to be increased for a few elements (see [WCAG 2.0 SC 1.4.3 Contrast][1]).

The filter list items (currently **"Fall 2018"** and **"Computer Science"**) need higher CCRs.

[1]: https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html

Related: #57, #60

**Comment by jylin7** [comment]
I did my own check on the items. It seems to have a 7.46:1 CCR already.

**Comment by tdy** [comment]
Yeah this was fixed in 54fda79.
